docs: add README files for Rust and Node.js
blc-org/una pull request #36
Opened 2022-10-25 13:58 UTC by Dolu89

Add some documentation in README.md (for Rust and Node.js)
#20

2022-10-25 14:02 UTC, louneskmt requested changes

2022-10-25 14:02 UTC, louneskmt commented on README.md
> +una-cli -- --backend LndRest --url https://127.0.0.1:8081 --macaroon HEX_MACAROON --tls_certificate HEX_CERTIFICATE
```suggestion
una-cli --backend LndRest --url https://127.0.0.1:8081 --macaroon HEX_MACAROON --tls_certificate HEX_CERTIFICATE
```
I don't think we need those if we execute the binary and not `cargo run`

2022-10-25 14:02 UTC, louneskmt commented on bindings/una-js/README.md
> +# Python bindings for UNA
```suggestion
# Node bindings for UNA
```

2022-10-25 14:02 UTC, louneskmt commented on README.md
> +Una is a Lightning network node wrapper for multiple backends and for multiple programming languages
```suggestion
Una is a Lightning network node wrapper for multiple backends and for multiple programming languages.
```

2022-10-25 14:35 UTC, Dolu89 commented on README.md
> +una-cli -- --backend LndRest --url https://127.0.0.1:8081 --macaroon HEX_MACAROON --tls_certificate HEX_CERTIFICATE
I tried, yes it's useless using the binary

2022-10-25 16:32 UTC, louneskmt commented
We should be a bit for explicit about Una on the bindings README, don't you think? These will be the README of each package, they are not just subdirs README.

2023-03-04 15:17 UTC, louneskmt commented
Looks good for now 👌

We will try in the future to have a docs website like the old LND REST API one, where you could see examples in several languages.

2023-03-04 15:17 UTC, louneskmt commented
Should we merge this yet @Dolu89?

2023-03-04 15:20 UTC, Dolu89 commented
> Should we merge this yet @Dolu89?

Yes

2023-03-04 18:54 UTC, louneskmt approved these changes

2023-03-04 18:54 UTC, merged

2023-03-04 18:54 UTC, louneskmt commented
Merged, thank you!